import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const navs = [
    {name: 'Blogs', href: '/blog'},
    {name: 'Products', href: '/products'}
  ]

  return (
    <html lang="en">
      

      <body className={inter.className}>
        {/* Navbar */}
        <div className="flex justify-evenly bg-orange-600 my-5 p-5">
          {navs.map(nav => (
            <Link className="text-3xl text-center text-white font-bold" key={nav.href} href={nav.href}>{nav.name}</Link>
          ))}
        </div>

          {/* <div className='mx-10 bg-green-600 text-white py-10 px-5 text-3xl'>
            {children}
          </div> */}
          {children}

        {/* Footer */}
        <div className="my-5">
          <h1 className="text-5xl text-center bg-red-600 rounded text-white font-bold p-5">Footer</h1>
        </div>
      </body>
    </html>
  )
}
